
PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

DIM        = 2
#DIM       = 3

COMP	   = gnu

USE_MPI    = FALSE
USE_OMP    = FALSE
USE_CUDA   = FALSE
USE_PARTICLES = FALSE
USE_BITTREE = FALSE

Bpack   := ./Make.package
Blocs   := .

include Make.Adv
